config/routes.rb
Rails.application.routes.draw do

  get 'issue_notes/new'

  get 'credit_debit_notes/new'

  get 'exempt_invoices/new'

  get 'export_invoices/new'

  resources :unit_of_measures
  resources :business_sales
  resources :customers do 
    collection do
      get :add_item
      post :add
      get :load_customer_data
    end
  end

  resources :invoices do
    member do
      get :show_invoice
    end
  end

  resources :export_invoices do
     member do
      get :show_export_invoice
    end
  end


   resources :exempt_invoices do
     member do
      get :show_exempt_invoice
    end
  end


   resources :credit_debit_notes do
     member do
      get :show_credit_debit_note
    end
  end

  resources :issue_notes do
     member do
      get :show_issue_note
    end
  end

 

  resources :customer_items do
   collection do
    post :create
    get :index
   end
   member do
    delete :destroy
  end
  end

   get 'invoices/attributes_for/:model' => 'invoices#get_attributes_for'
  
  resources :items do
    collection do
      get :load_item_data
    end
  end
  resources :parties
  resources :charted_accountants
   devise_for :users, controllers: { registrations: 'registrations' }
   as :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
   end
  root 'home#dashboard'
  # get 'dashboard/index'
  resources :tables do
    collection do
     get :basic_tables
   end
 end
  # defaults to dashboard
  # root :to => redirect('/dashboard')
  resources :users do
    collection do
      get :index
    end
  end
  
  resources :home do
    collection do 
    get :dashboard
    end
  end

  resources :general_settings
  # view routes
  # get '/dashboard' => 'dashboard#index'

 
end

app/models/party.rb
class Party < ApplicationRecord

	after_save :create_user_account
  has_attached_file :image
  has_many :users
  has_many :customers
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

    def create_user_account
    	# @user = User.create!(first_name: self.party_name, username: self.email, party_id: self.id, password: self.party_no, role: 'Party',email: self.email)
    end

   def self.set_party_no
    date = Date.today.strftime('%Y%m%d')
    if Party.first.nil?
      'S' + date.to_s + '1'
    else
      last_id = Party.last.id.next
      'S' + date.to_s + last_id.to_s
    end
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    if current_user.role == "ChartedAccountant"
     @parties = current_user.charted_accountant.parties
   elsif current_user.role == "SuperAdmin"
     @parties = Party.all
     @general_setting = GeneralSetting.first
   else
     @parties = current_user.party
   end
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
    @general_setting = GeneralSetting.first
  end

  # GET /parties/new
  def new
    @party = Party.new
    @party.party_no = Party.set_party_no
    @general_setting = GeneralSetting.first
  end

  # GET /parties/1/edit
  def edit
    @general_setting = GeneralSetting.first
  end

  # POST /parties
  # POST /parties.json
  def create
    @party = Party.new(party_params)
      if current_user.role == 'ChartedAccountant'
        @party.update!(:charted_accountant_id => current_user.charted_accountant.id) 
        User.create!(first_name: @party.party_name, username: @party.email, party_id: @party.id, password: @party.party_no, role: 'Party',email: @party.email)
      else
        @party.save
      if current_user.role == 'Party'
        current_user.party_id = @party.id
        current_user.save
      end
     end
    @party.save
    @user = User.create!(first_name: @party.party_name, username: @party.email, party_id: @party.id, password: @party.party_no, role: 'Party', email: @party.email)
    redirect_to party_path
    end
  

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
      @general_setting = GeneralSetting.first
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:composite, :regular,:image,:email,:party_no,:party_name, :party_gstin_no, :party_arn_no, :party_address, :place_of_supply, :commodity_name, :tarrif_no, :hsn_no, :rate_of_tax, :name_service, :service_acc_code, :party_pan_no, :state_name, :state_code, :ca_name, :ca_contact)
    end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
  <div class="pageheader">
                <h1>New Party</h1>
                <div class="breadcrumb-wrapper hidden-xs">
                    <span class="label">You are here:</span>
                    <ol class="breadcrumb">
                        <li><a href="/">Dashboard</a>
                        </li>
                        <li class="active">New Party</li>
                    </ol>
                </div>
            </div>
            <section id="main-content" class="animated fadeInUp">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">New Party</h3>
                                <div class="actions pull-right">
                                 <i class="fa fa-expand"></i>
                                    <i class="fa fa-chevron-down"></i>
                                    <i class="fa fa-times"></i>
                                </div>
                            </div>
                            <div class="panel-body">
                           
                           <%= form_with(model: party, local: true) do |f| %>
                              <% if party.errors.any? %>
                                <div id="error_explanation">
                                  <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

                                  <ul>
                                  <% party.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                  <% end %>
                                  </ul>
                                </div>
                              <% end %>
                                <form class="form-horizontal">
                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-10 control-label">Party Name</label>
                                          <%= f.text_field :party_name,class: "form-control",placeholder: "Party Name."%>
                                      </div>
                                    </div>

                                  <%if current_user.role == 'Party'%>
                                    <!-- <div class="form-group">
                                       <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">Email</label>
                                          <%#= f.text_field :email, :value => current_user.email,class: "form-control",readonly:true%>
                                       </div>
                                    </div> -->
                                  <%else%>
                                    <div class="form-group">
                                       <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">Email</label>
                                          <%= f.text_field :email,class: "form-control"%>
                                       </div>
                                    </div>
                                  <%end%>

                                  <%if current_user.role == 'Party'%>

                                  <%else%>
                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">Party No</label>
                                          <%= f.text_field :party_no,class: "form-control",placeholder: "Party No.", readonly:true%>
                                      </div>
                                    </div>
                                  <%end%>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">GST No</label>
                                          <%= f.text_field :party_gstin_no, class: "form-control" ,placeholder: "Gst No."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">ARN No</label>
                                          <%= f.text_field :party_arn_no, class: "form-control", placeholder: "ARN No."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">Address</label>
                                          <%= f.text_field :party_address, class: "form-control" ,placeholder: "Address."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-12 control-label">Place Of Supply</label>
                                          <%= f.text_field :place_of_supply, class: "form-control",placeholder: "Place of supply."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-10 control-label">Commodity Name</label>
                                          <%= f.text_field :commodity_name, class: "form-control" ,placeholder: "No."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">Tarrif No</label>
                                          <%= f.text_field :tarrif_no, class: "form-control" ,placeholder: "No."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">HSN No</label>
                                         <%= f.text_field :hsn_no, class: "form-control" ,placeholder: "No."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-10 control-label">Rate Of Tax</label>
                                         <%= f.text_field :rate_of_tax, class: "form-control" ,placeholder: "Tax Rate."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-10 control-label">Name Service</label>
                                          <%= f.text_field :name_service, class: "form-control" ,placeholder: "Name."%>
                                      </div>
                                    </div>

                                     <div class="form-group">
                                       <div class="col-sm-3">
                                        <label class="col-sm-15 control-label">Service Accounting Code</label>
                                          <%= f.text_field :service_acc_code, class: "form-control" ,placeholder: "Code."%>
                                        </div>
                                    </div>


                                     <div class="form-group">
                                       <div class="col-sm-3">
                                        <label class="col-sm-6 control-label">PAN NO</label>
                                          <%= f.text_field :party_pan_no, class: "form-control" ,placeholder: "PAN No."%>
                                       </div>
                                    </div>

                                    <div class="form-group">
                                       <div class="col-sm-3">
                                        <label class="col-sm-10 control-label">State Name</label>
                                            <%= f.text_field :state_name, class: "form-control" ,placeholder: "State Name."%>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-10 control-label">State Code</label>
                                            <%= f.text_field :state_code, class: "form-control" ,placeholder: "State Code."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-10 control-label">CA Name</label>
                                            <%= f.text_field :ca_name, class: "form-control" ,placeholder: "CA Name."%>
                                      </div>
                                    </div>

                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-10 control-label">CA Contact</label>
                                            <%= f.text_field :ca_contact , class: "form-control" ,placeholder: "Conatct."%>
                                        </div>
                                    </div>



                                    <div class="form-group">
                                      <div class="col-sm-3">
                                        <label class="col-sm-15 control-label">Upload Profile Image</label>
                                            <%=f.file_field :image,class: "form-control"%>
                                      </div>
                                    </div>

                                  

                                    <div class="panel-body">
                                      <div class="col-sm-offset-3 col-sm-12">
                                        <%= f.submit class: "btn btn-success"%>
                                        <%= link_to 'Back', parties_path,class: "btn btn-primary" %>
                                      </div>
                                    </div>
                                
                                <%end%>
                            </div>
                        </div>
                    </div>
                </div>
        </section>

app/views/parties/edit.html.erb
<h1>Editing Party</h1>

<%= render 'form', party: @party %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
                <div class="row">
                    <div class="col-md-12">

                        <div class="panel panel-default">
                          <div class="panel-heading">
                            <h3 class="panel-title">View All Parties</h3>
                            <div class="actions pull-right">
                             <i class="fa fa-expand"></i>
                                <i class="fa fa-chevron-down"></i>
                                <i class="fa fa-times"></i>
                            </div>
                          </div>
                          <div class="panel-body">
                          <%if current_user.role == 'Party'%>
                          <%else%>
                             <%= link_to 'New Party', new_party_path, class: 'btn btn-link' %>
                          <%end%>
                            <div class="table-responsive">
                              <table class="table table-bordered table-striped">
                                <thead>
                                  <tr>
                                    <th>Party name</th>
                                    <th>Party gstin no</th>
                                    <th>Party arn no</th>
                                    <th>Place of supply</th>
                                    <th>Commodity name</th>
                                    <th>State Name</th>
                                    <th>State Code</th>
                                   
                                   
                                    <th colspan="3"></th>
                                  </tr>
                                </thead>

                                <tbody>
                                <%if current_user.role == 'Party'%>
                                
                                  <tr>
                                      <td><%= @parties.party_name %></td>
                                      <td><%= @parties.party_gstin_no %></td>
                                      <td><%= @parties.party_arn_no %></td>
                                      <td><%= @parties.commodity_name %></td>
                                      <td><%= @parties.state_name %></td>
                                      <td><%= @parties.state_code %></td>
                                     
                                     
                                  </tr>
                                <%else%>  
                                  <% @parties.each do |party| %>
                                    <tr>
                                      <td><%= party.party_name %></td>
                                      <td><%= party.party_gstin_no %></td>
                                      <td><%= party.party_arn_no %></td>
                                      <td><%= party.party_address %></td>
                                      <td><%= party.commodity_name %></td>
                                      <td><%= party.state_name %></td>
                                      <td><%= party.state_code %></td>
                                      <td><%= %></td>
                                      <td><%= link_to 'Show', party %></td>
                                      <td><%= link_to 'Edit', edit_party_path(party) %></td>
                                      <td><%= link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                    </tr>
                                  <% end %>
                                  <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>
             </div>
<br>

app/views/parties/new.html.erb
<%= render 'form', party: @party %>

app/views/parties/show.html.erb
        <section class="main-content-wrapper">
            <!-- Main content view  -->
                  <div class="pageheader">
                <h1>View All Party Details</h1>
                <div class="breadcrumb-wrapper hidden-xs">
                    <span class="label">You are here:</span>
                    <ol class="breadcrumb">
                        <li><a href="/">Dashboard</a>
                        </li>
                        <li>UI Elements</li>
                        <li class="active">Panels</li>
                    </ol>
                </div>
            </div>
            <section id="main-content" class="animated fadeInUp">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                               <p>
  <strong>Party name:</strong>
  <%= @party.party_name %>
</p>

<p>
  <strong>Party gstin no:</strong>
  <%= @party.party_gstin_no %>
</p>

<p>
  <strong>Eamil Address:</strong>
  <%= @party.email %>
</p>

<p>
  <strong>Party No:</strong>
  <%= @party.party_no %>
</p>

<p>
  <strong>Party arn no:</strong>
  <%= @party.party_arn_no %>
</p>

<p>
  <strong>Party address:</strong>
  <%= @party.party_address %>
</p>

<p>
  <strong>Place of supply:</strong>
  <%= @party.place_of_supply %>
</p>

<p>
  <strong>Commodity name:</strong>
  <%= @party.commodity_name %>
</p>

<p>
  <strong>Tarrif no:</strong>
  <%= @party.tarrif_no %>
</p>

<p>
  <strong>Hsn no:</strong>
  <%= @party.hsn_no %>
</p>

<p>
  <strong>Rate of tax:</strong>
  <%= @party.rate_of_tax %>
</p>

<p>
  <strong>Name service:</strong>
  <%= @party.name_service %>
</p>

<p>
  <strong>Service acc code:</strong>
  <%= @party.service_acc_code %>
</p>

<p>
  <strong>Party pan no:</strong>
  <%= @party.party_pan_no %>
</p>

<p>
  <strong>State name:</strong>
  <%= @party.state_name %>
</p>

<p>
  <strong>State code:</strong>
  <%= @party.state_code %>
</p>

<p>
  <strong>Ca name:</strong>
  <%= @party.ca_name %>
</p>

<p>
  <strong>Ca contact:</strong>
  <%= @party.ca_contact %>
</p>

                            </div>
                        </div>
                    </div>
                </div>
                <%= link_to 'Back', parties_path,class: "btn btn-primary" %>