config/routes.rb
Rails.application.routes.draw do

  get 'issue_notes/new'

  get 'credit_debit_notes/new'

  get 'exempt_invoices/new'

  get 'export_invoices/new'

  resources :unit_of_measures
  resources :business_sales
  resources :customers do 
    collection do
      get :add_item
      post :add
      get :load_customer_data
    end
  end

  resources :invoices do
    member do
      get :show_invoice
    end
  end

  resources :export_invoices do
     member do
      get :show_export_invoice
    end
  end


   resources :exempt_invoices do
     member do
      get :show_exempt_invoice
    end
  end


   resources :credit_debit_notes do
     member do
      get :show_credit_debit_note
    end
  end

  resources :issue_notes do
     member do
      get :show_issue_note
    end
  end

 

  resources :customer_items do
   collection do
    post :create
    get :index
   end
   member do
    delete :destroy
  end
  end

   get 'invoices/attributes_for/:model' => 'invoices#get_attributes_for'
  
  resources :items do
    collection do
      get :load_item_data
    end
  end
  resources :parties
  resources :charted_accountants
   devise_for :users, controllers: { registrations: 'registrations' }
   as :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
   end
  root 'home#dashboard'
  # get 'dashboard/index'
  resources :tables do
    collection do
     get :basic_tables
   end
 end
  # defaults to dashboard
  # root :to => redirect('/dashboard')
  resources :users do
    collection do
      get :index
    end
  end
  
  resources :home do
    collection do 
    get :dashboard
    end
  end

  resources :general_settings
  # view routes
  # get '/dashboard' => 'dashboard#index'

 
end

app/models/unit_of_measure.rb
class UnitOfMeasure < ApplicationRecord
	has_many :items
end

app/controllers/unit_of_measures_controller.rb
class UnitOfMeasuresController < ApplicationController
  before_action :set_unit_of_measure, only: [:show, :edit, :update, :destroy]

  # GET /unit_of_measures
  # GET /unit_of_measures.json
  def index
    @unit_of_measures = UnitOfMeasure.all
  end

  # GET /unit_of_measures/1
  # GET /unit_of_measures/1.json
  def show
  end

  # GET /unit_of_measures/new
  def new
    @unit_of_measure = UnitOfMeasure.new
  end

  # GET /unit_of_measures/1/edit
  def edit
  end

  # POST /unit_of_measures
  # POST /unit_of_measures.json
  def create
    @unit_of_measure = UnitOfMeasure.new(unit_of_measure_params)

    respond_to do |format|
      if @unit_of_measure.save
        format.html { redirect_to @unit_of_measure, notice: 'Unit of measure was successfully created.' }
        format.json { render :show, status: :created, location: @unit_of_measure }
      else
        format.html { render :new }
        format.json { render json: @unit_of_measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unit_of_measures/1
  # PATCH/PUT /unit_of_measures/1.json
  def update
    respond_to do |format|
      if @unit_of_measure.update(unit_of_measure_params)
        format.html { redirect_to @unit_of_measure, notice: 'Unit of measure was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit_of_measure }
      else
        format.html { render :edit }
        format.json { render json: @unit_of_measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_of_measures/1
  # DELETE /unit_of_measures/1.json
  def destroy
    @unit_of_measure.destroy
    respond_to do |format|
      format.html { redirect_to unit_of_measures_url, notice: 'Unit of measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit_of_measure
      @unit_of_measure = UnitOfMeasure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_of_measure_params
      params.require(:unit_of_measure).permit(:name)
    end
end

app/helpers/unit_of_measures_helper.rb
module UnitOfMeasuresHelper
end

app/views/unit_of_measures/_form.html.erb
  <div class="pageheader">
                <h1>Create New Item</h1>
                <div class="breadcrumb-wrapper hidden-xs">
                    <span class="label">You are here:</span>
                    <ol class="breadcrumb">
                        <li><a href="/">Dashboard</a>
                        </li>
                        <li>Forms</li>
                        <li class="active">New Unit of Measure</li>
                    </ol>
                </div>
            </div>
            <section id="main-content" class="animated fadeInUp">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">New Item</h3>
                                <div class="actions pull-right">
                                 <i class="fa fa-expand"></i>
                                    <i class="fa fa-chevron-down"></i>
                                    <i class="fa fa-times"></i>
                                </div>
                            </div>
                            <div class="panel-body">
<%= simple_form_for(@unit_of_measure) do |f| %>
  <%= f.error_notification %>

    <div class="form-group">
      <div class="col-sm-3">
         <label class="col-sm-20 control-label">Unit of Measure</label>
        <%= f.input :name , class: 'form-control'%>
    </div>
    </div>

        <br><br><br><br>
                             
                                     <div class="panel-body">
                                        <div class="col-sm-offset-3 col-sm-12">
                                        <%= f.submit class: "btn btn-success"%>
                                        <%= link_to 'Back', items_path,class: "btn btn-primary" %>
                                         <%= link_to 'View All UOM', unit_of_measures_path,class: "btn btn-danger" %>
                                        </div>
                                    </div>
                                 
                                <%end%>
                            </div>
                        </div>
                    </div>
                </div>
        </section>

app/views/unit_of_measures/edit.html.erb
<%= render 'form', unit_of_measure: @unit_of_measure %>

<%= link_to 'Show', @unit_of_measure %> |
<%= link_to 'Back', unit_of_measures_path %>

app/views/unit_of_measures/index.html.erb
        <section class="main-content-wrapper">
            <!-- Main content view  -->
                             <div class="pageheader">
                <h1>View All Items</h1>
                <div class="breadcrumb-wrapper hidden-xs">
                    <span class="label">You are here:</span>
                    <ol class="breadcrumb">
                        <li><a href="/">Dashboard</a>
                        </li>
                        <li>Tables</li>
                        <li class="active">View Unit of Measure</li>
                    </ol>
                </div>
            </div>
            <section id="main-content" class="animated fadeInUp">
                      <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                          <div class="panel-heading">
                            <h3 class="panel-title">Unit of Measure</h3>
                            <div class="actions pull-right">
                             <i class="fa fa-expand"></i>
                                <i class="fa fa-chevron-down"></i>
                                <i class="fa fa-times"></i>
                            </div>
                          </div>
                          <div class="panel-body">
                            <%= link_to 'Add Unit of Measure', new_unit_of_measure_path, class: 'btn btn-primary' %> |  <%= link_to 'Add Items', new_item_path, class: 'btn btn-success' %>
                        <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                          <thead>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unit_of_measures.each do |unit_of_measure| %>
      <tr>
        <td><%= unit_of_measure.name %></td>
        <td><%= link_to 'Show', unit_of_measure %></td>
        <td><%= link_to 'Edit', edit_unit_of_measure_path(unit_of_measure) %></td>
        <td><%= link_to 'Destroy', unit_of_measure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
 </table>
                         
                       </div>
                     </div>
                </div>
            </div>
              </section>
<br>

app/views/unit_of_measures/new.html.erb
<%= render 'form', unit_of_measure: @unit_of_measure %>

app/views/unit_of_measures/show.html.erb
<section class="main-content-wrapper">
                  <div class="pageheader">
                <h1>View All Details</h1>
                <div class="breadcrumb-wrapper hidden-xs">
                    <span class="label">You are here:</span>
                    <ol class="breadcrumb">
                        <li><a href="/">Dashboard</a>
                        </li>
                        <li class="active">Unit of Measure Details</li>
                    </ol>
                </div>
            </div>
            <section id="main-content" class="animated fadeInUp">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
<p>
  <strong>Name:</strong>
  <%= @unit_of_measure.name %>
</p>

<%= link_to 'Edit', edit_unit_of_measure_path(@unit_of_measure),class: "btn btn-primary" %> |
<%= link_to 'Back', unit_of_measures_path,class: "btn btn-primary" %>