config/routes.rb
Rails.application.routes.draw do

  get 'issue_notes/new'

  get 'credit_debit_notes/new'

  get 'exempt_invoices/new'

  get 'export_invoices/new'

  resources :unit_of_measures
  resources :business_sales
  resources :customers do 
    collection do
      get :add_item
      post :add
      get :load_customer_data
    end
  end

  resources :invoices do
    member do
      get :show_invoice
    end
  end

  resources :export_invoices do
     member do
      get :show_export_invoice
    end
  end


   resources :exempt_invoices do
     member do
      get :show_exempt_invoice
    end
  end


   resources :credit_debit_notes do
     member do
      get :show_credit_debit_note
    end
  end

  resources :issue_notes do
     member do
      get :show_issue_note
    end
  end

 

  resources :customer_items do
   collection do
    post :create
    get :index
   end
   member do
    delete :destroy
  end
  end

   get 'invoices/attributes_for/:model' => 'invoices#get_attributes_for'
  
  resources :items do
    collection do
      get :load_item_data
    end
  end
  resources :parties
  resources :charted_accountants
   devise_for :users, controllers: { registrations: 'registrations' }
   as :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
   end
  root 'home#dashboard'
  # get 'dashboard/index'
  resources :tables do
    collection do
     get :basic_tables
   end
 end
  # defaults to dashboard
  # root :to => redirect('/dashboard')
  resources :users do
    collection do
      get :index
    end
  end
  
  resources :home do
    collection do 
    get :dashboard
    end
  end

  resources :general_settings
  # view routes
  # get '/dashboard' => 'dashboard#index'

 
end

app/models/exempt_invoice.rb
class ExemptInvoice < ApplicationRecord
  belongs_to :customer
  has_many :exempt_invoice_items, inverse_of: :exempt_invoice
  accepts_nested_attributes_for :exempt_invoice_items, reject_if: :all_blank, allow_destroy: true
  scope :shod, ->(id) { where(id: id).take }

  def self.set_invoice_no
    date = Date.today.strftime('%d')
    if ExemptInvoice.first.nil?
      'EXEMPT' + date.to_s + '1'
    else
      last_id = ExemptInvoice.last.id.next
      'EXEMPT' + date.to_s + last_id.to_s
    end
  end
end

app/controllers/exempt_invoices_controller.rb
class ExemptInvoicesController < ApplicationController
  def index
   @exempt_invoices = ExemptInvoice.all
 end

 def new
  @exempt_invoice = ExemptInvoice.new
    @exempt_invoice.exempt_invoice_items.build # build ingredient attributes, nothing new here
    @exempt_invoice.exempt_invoice_number = ExemptInvoice.set_invoice_no
    @items = Item.all
  end

  def create
    @exempt_invoice = ExemptInvoice.new(export_invoice_params)
    if @exempt_invoice.save
      flash[:notice] = "Successfully Created Invoice"
      redirect_to @exempt_invoice and return
    end
  end

  def edit
   @exempt_invoice = ExemptInvoice.find(params[:id])
  end

 def update
  @exempt_invoice = ExemptInvoice.find(params[:id])
  respond_to do |format|
    if @exempt_invoice.update(export_invoice_params)
      format.html { redirect_to invoice_path, notice: 'invoice was successfully updated.' }
      format.json { render :index, status: :ok, location: @exempt_invoice }
    else
      format.html { render :edit }
      format.json { render json: @exempt_invoice.errors, status: :unprocessable_entity }
    end
  end
end

def destroy
  @exempt_invoice = ExemptInvoice.find(params[:id])
  @exempt_invoice.destroy
  flash[:notice] = "Successfully destroyed Invoice"
  redirect_to @exempt_invoice
end

def show
  @exempt_invoice = ExemptInvoice.find(params[:id])
  respond_to do |format|
    format.html
    format.pdf do
        render pdf: "show_exempt_invoice.pdf.erb"   # Excluding ".pdf" extension.
      end
    end
  end

  def show_exempt_invoice
   @exempt_invoice = ExemptInvoice.find(params[:id])
   respond_to do |format|
    format.html
    format.pdf do
        render pdf: "show_exempt_invoice.pdf.erb"   # Excluding ".pdf" extension.
      end
    end
  end
  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def export_invoice_params
      params.require(:exempt_invoice).permit(:customer_id, :exempt_invoice_number,:exempt_invoice_date,exempt_invoice_items_attributes:[ :unit_price, :quantity,:item_id,:rate, :qty, :net_amt, :sgst, :cgst, :tax_rate, :tax_amt, :total_amt,:_destroy])
    end
end

app/helpers/exempt_invoices_helper.rb
module ExemptInvoicesHelper
end

app/views/exempt_invoices/index.html.erb
        <section class="main-content-wrapper">
          <!-- Main content view  -->
          <div class="pageheader">
            <h1>Exempt Invoices</h1>
            <div class="breadcrumb-wrapper hidden-xs">
              <span class="label">You are here:</span>
              <ol class="breadcrumb">
                <li><a href="/">Dashboard</a>
                </li>
                <li>Tables</li>
                <li class="active">View Exempt Invoices</li>
              </ol>
            </div>
          </div>
          <section id="main-content" class="animated fadeInUp">
            <div class="row">
              <div class="col-md-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Exempt Invoices</h3>
                    <div class="actions pull-right">
                     <i class="fa fa-expand"></i>
                     <i class="fa fa-chevron-down"></i>
                     <i class="fa fa-times"></i>
                   </div>
                 </div>
                 <div class="panel-body">
                  <%= link_to 'Add Invoices', new_exempt_invoice_path, class: 'btn btn-primary' %>
                  <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                      <thead>
                        <tr>
                          <th>Invoice Number</th>
                          <th>Date of Invoice</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @exempt_invoices.each_with_index do |a,i| %>
                        <tr>
                          <td><%=i+1%></td>
                          <td><%=a.exempt_invoice_number %></td>
                          <td><%=a.exempt_invoice_date %></td>
                          <td><%= link_to 'View Invoice', exempt_invoice_path(a)%></td>
                          <td><%= link_to 'Destroy',exempt_invoice_path(a), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                    
                  </div>
                </div>
              </div>
            </div>
          </section>
          <br>

app/views/exempt_invoices/new.html.erb
<div class="pageheader">
  <h1>New NILL RATED/EXEMPT Invoice</h1>
  <div class="breadcrumb-wrapper hidden-xs">
    <span class="label">You are here:</span>
    <ol class="breadcrumb">
      <li><a href="/">Dashboard</a>
      </li>
      <li>Forms</li>
      <li class="active">New NILL RATED/EXEMPT Invoice</li>
    </ol>
  </div>
</div>

<section id="main-content" class="animated fadeInUp">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">NILL RATED/EXEMPT</h3>
          <div class="actions pull-right">
           <i class="fa fa-expand"></i>
           <i class="fa fa-chevron-down"></i>
           <i class="fa fa-times"></i>
         </div>
       </div>
       <div class="panel-body">
        <%= nested_form_for @exempt_invoice, url: {action:'create', controller: 'exempt_invoices'} do |f|%>

        <form class="form-horizontal">
          <div class="form-group">

            <div class="form-group">
              <div class="col-sm-3">
                <label class="col-sm-10 control-label">Invoice Number</label>   
                <%= f.text_field :exempt_invoice_number,class: 'form-control', readonly:true%>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-3">
                <label class="col-sm-10 control-label">Date</label>   
                <%= f.date_field :exempt_invoice_date,value: Date.today, class: 'form-control'%>
              </div>
            </div>


            <div class="form-group">
              <div class="col-sm-3">
                <label class="col-sm-10 control-label">Search Customers</label>           <%=f.select :customer_id ,Customer.all.collect{|i| [i.customer_name, i.id]}, {prompt:true},class: "form-control"%>
              </div>
            </div>
            

            <div class="form-group">
              <div class="col-sm-3">
                <label class="col-sm-6 control-label">Address</label>   
                <input type="address" name="address" id="address" class="form-control"></td>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-3">
                <label class="col-sm-6 control-label">GST No</label>   
                <input type="gstin_no_reg" name="gstin_no_reg" id="gstin_no_reg" class="form-control"></td>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-3">
                <label class="col-sm-6 control-label">PAN No</label>   
                <input type="cust_pan_no" name="cust_pan_no" id="cust_pan_no" class="form-control"></td>
              </div>
            </div>



            <br><br><br><br><br><br>



            <div class="panel-body">

              <div class="table-responsive">
                <table id="example"  class="table table-bordered table-striped" cellspacing="0" width="100%">
                  <thead>
                   <tr>
                    <th width="135"><h6>Description</h6></th>
                    <th width="185"><h6>Unit-Price</h6></th>
                    <th width="185"><h6>Quantity</h6></th>
                    <th width="185"><h6>Net Amt</h6></th>
                    <th width="185"><h6>Total Amt</h6></th>
                    <th><h6>Action&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h6></th>
                  </tr>
                </thead>
                
              </table>
              

              <%= f.fields_for :exempt_invoice_items, :wrapper => false do |invoice_item| %>
              
              <div class="table-responsive">
                <table id="example"  class="table table-bordered table-striped" cellspacing="0" width="100%">
                  <colgroup>
                  <col class="one"/>
                  <col class="two"/>
                  <col class="three"/>
                  <col class="four"/>
                  <col class="five"/>
                  <col class="six"/>
                  <col class="seven"/>
                  <col class="eight"/>
                </colgroup>

                
                <tr class="fields">
                  
                  
                  <td> <%=invoice_item.select :item_id ,Item.all.collect{|i| [i.dogns,i.rate, i.id]}, {prompt:true},class: "select"%></td>
                  <td><%= invoice_item.text_field :unit_price, id: :rate, class: 'form-control'%></td>
                  <td><%= invoice_item.text_field :quantity, id: :qty, class: 'form-control'%></td>
                  <td><%= invoice_item.text_field :net_amt, id: :net_amt, class: 'form-control'%></td>
                 
                  <td><%= invoice_item.text_field :total_amt, id: :total_amt, class: 'form-control'%></td>
                  
                  <td><%= invoice_item.link_to_remove "Remove", class: 'btn btn-info' %></td>
                </tr>
              </table>

            </div>
            <!--grid_table-->
            


            <% end %>
            <td><%= f.link_to_add "Add Item", :exempt_invoice_items , class: 'btn btn-danger' %></td>
            <div class="pull-right">
              <p><%= f.submit "Create Invoice", class: 'btn btn-success' %></p>
            </div>
            <% end %>

          </section>
        </div>
      </div>
    </div>
  </div>
</div>
</div>




<% content_for :javascript do %>
<script type="text/javascript">

  $(document).ready(function() {
    $('select#exempt_invoice_customer_id').select2({
      placeholder: "Choose a customers",
      allowClear: true
    });
  });
</script>
<% end %>

<% content_for :javascript do %>
<script type="text/javascript">
  $("#exempt_invoice_customer_id").on("change", function() {
    var customer_id;
    Item = $(this).val();
    $.ajax({
      url: "/customers/load_customer_data",
      type: "GET",
      data: {customer_id: Item },
      dataType: "json"
    }).done(function (data) {
     console.log(data);
     $("#address").val(data[0]);
     $("#gstin_no_reg").val(data[1]);
     $("#cust_pan_no").val(data[2]);
      // $("#uom").val(data[1]);
      // $("#rate").val(data[2]);
      
    });
  });
</script>
<% end %>





<% content_for :javascript do %>
<script type="text/javascript">
  $(document).on("change", ".select", function () {
    var item_id = $(this);
    elem = jQuery(this);
    $.ajax({
      url: "/items/load_item_data",
      type: 'GET',
      dataType: 'html',
      data: {item_id: $(this).val()},
      success: function (data) {
        console.log(data);
        item = JSON.parse(data);
        container = elem.parents("tr.fields");
        container1 = elem.parents("th.fields");
        container.find("#rate").val(item[0]);
        container.find("#cgst").val(item[1]);
        container.find("#sgst").val(item[2]);

      }
    });

  });
</script>
<% end %>

<% content_for :javascript do %>
<script type="text/javascript">
 $(document).on("keyup", "#rate, #qty", function() {
  container = elem.parents("tr.fields");
  var val1 = +container.find("#rate").val();
  var val2 = +container.find("#qty").val();
  +container.find("#net_amt").val(val1*val2);

  +container.find('#total_amt').val(val1*val2);
});


 function deleteRow(btn) {
  var row = btn.parentNode;
  row.parentNode.removeChild(row);
}

</script>
<%end%>

<% content_for :javascript do %>
<script type="text/javascript">
  $(document).on('nested:fieldAdded', function(event){
  // this field was just inserted into your form
  var field = event.field; 
  var selectField = field.find('.select');
  selectField.select2();
  // and activate datepicker on it
//  dateField.datepicker();
})
</script>
<% end %>



<% content_for :javascript do %>
<script type="text/javascript">
  $(document).ready(function() {
    $('select#exempt_invoice_exempt_invoice_items_attributes_0_item_id').select2({
    });
  });
</script>
<% end %>

app/views/exempt_invoices/show.html.erb
 <div class="pageheader">
   <div class="row">
    <div class="col-md-12">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">Exempt Invoice</h3>
          <div class="actions pull-right">
           <i class="fa fa-expand"></i>
           <i class="fa fa-chevron-down"></i>
           <i class="fa fa-times"></i>
         </div>
       </div>
       <div class="panel-body">
         <div class="pull-right">
        <%= link_to 'Download PDF ',show_exempt_invoice_exempt_invoice_path(@exempt_invoice, format: 'pdf'),target: '_blank', class: "btn btn-primary"%> <b> | </b> <%=link_to 'Back', exempt_invoices_path, class: 'btn btn-success'%></div>

      <div class="row">
             <div class="col-md-4">
             <div class="pull-left">
            <p><strong>Invoice Number:</strong>
              <%=@exempt_invoice.exempt_invoice_number%></p>
              <p><strong>Date:</strong>
                <%=@exempt_invoice.exempt_invoice_date%></p>
                <p> <strong>Customer Name:</strong>
                 <%=@exempt_invoice.customer.customer_name%></p>
                 <p> <strong>Address:</strong>
                   <%=@exempt_invoice.customer.address%></p>
                   <p> <strong>GSTIN No:</strong>
                     <%=@exempt_invoice.customer.gstin_no_reg%></p>
                     <br>
                   </div></div>

                 
                     <div class="col-md-4 col-sm-offset-8">
                      <div class="pull-right">
                      <p><strong>Sold By:</strong>
                        <%=current_user.party.party_name%></p>
                        <p><strong>Date:</strong>
                          <%=@exempt_invoice.exempt_invoice_date%></p>
                          <p> <strong>Address:</strong>
                           <%=current_user.party.party_address%></p>
                           
                           <p> <strong>GSTIN No:</strong>
                             <%=current_user.party.party_gstin_no%></p>
                             <p> <strong>PAN No</strong>
                               <%=current_user.party.party_pan_no%></p>
                               <br>
                             </div></div></div>

                             <div class="table-responsive">
                              <table class="table table-bordered table-striped">
                                <thead>
                                  <tr>
                                   <th>Sr No</th>
                                   <th>Item Description</th>
                                   <th>HSN/SAC</th>
                                   <th>UOM</th>
                                   <th>Unit Price</th>
                                   <th>Quantity</th>
                                   <th>Net Amount</th>
                             
                                 </tr>
                               </thead>

                               <tbody>
                                <%tax_amt = 0%>
                                <%total_amt = 0%>
                                <% @exempt_invoice.exempt_invoice_items.each_with_index do |i,n|%>
                                <tr>
                                  <td><%= n + 1 %></td>
                                  <td><%= i.item.dogns%></td>
                                  <td><%= i.item.item_hsn_no%></td>
                                  <td><%= i.item.unit_of_measure.name%></td>
                                  <td>&#8377;<%= i.unit_price%></td>
                                  <td><%= i.quantity%></td>
                                  <td>&#8377;<%= i.net_amt%></td>
                                </tr>
                                <% tax_amt += i.tax_amt.to_f%>
                                <%total_amt += i.total_amt.to_f%>
                                <% end %>
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <b>Total Amount </b>&#8377;<%=total_amt%><br>
                  <b>Discount </b> <%=text_field_tag :discount%>

                  <br>

                </div>
              </div>
            </div>
          </div>

app/views/exempt_invoices/show_exempt_invoice.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    table {
     width:100%;
   }
   table, th, td {
     border: 1px solid black;
     border-collapse: collapse;
     font-size: 12px;
   }
   th, td {
     padding: 2px;
     text-align: left;
   }
   table#t01 tr:nth-child(even) {
     background-color: #eee;
   }
   table#t01 tr:nth-child(odd) {
    background-color:#fff;
  }
  table#t01 th {
   background-color: black;
   color: white;
 }
  p{
    width: 250px;
   }
 h5 {
   display:inline;
 }
</style>
</head>
<body>

  <div class="center"><h2><b><font color="grey">EXEMPT Invoice</font></b></h2></div>
  <div id="heading">
   

    
    <div class align ="left">
      <p><strong>Sold By:</strong>
        <%=current_user.party.party_name%></p>
        <p><strong>Date:</strong>
          <%=@exempt_invoice.exempt_invoice_date%></p>
          <p> <strong>Address:</strong>
           <%=current_user.party.party_address%></p>
           
           <p> <strong>GSTIN No:</strong>
             <%=current_user.party.party_gstin_no%></p>
             <p> <strong>PAN No</strong>
               <%=current_user.party.party_pan_no%></p>
               
             </div>
             <div class align ="right">
               <p> <strong>Customer Name:</strong>
                 <%=@exempt_invoice.customer.customer_name%></p>
                 <p> <strong>Address:</strong>
                   <%=@exempt_invoice.customer.address%></p>
                   <p> <strong>GSTIN No:</strong>
                     <%=@exempt_invoice.customer.gstin_no_reg%></p>
                     
                     <br>
                     <br>
                     
                   </div>  
                   <div class align="left">
                     <p><strong>Invoice Number:</strong>
                      <%=@exempt_invoice.exempt_invoice_number%></p>
                      <p><strong>Invoice Date:</strong>
                        <%=@exempt_invoice.exempt_invoice_date%></p><br>
                      </div>
                      
                    </div>  
                  </div>  
                  <table class="table table-condensed table-bordered" style="margin-top: -15px; margin-bottom: 15px;">
                    <thead>
                      <tr>
                        <th style="font-size: 16px; background-color: #ccc; width: 75px;" colspan="11"><center>EXempt/ZERO RATED Invoice</center></th>
                      </tr>

                      <th>Sr No</th>
                      <th>Item Description</th>
                      <th>HSN/SAC</th>
                      <th>UOM</th>
                      <th>Unit Price</th>
                      <th>Quantity</th>
                      <th>Net Amount</th>
                      <th>Tax Rate</th>
                      <th>Tax Type</th>
                      <th>Tax Amount</th>
                      <th>Total Amount</th>
                    </tr>
                    <%tax_amt = 0%>
                    <%total_amt = 0%>

                    <% @exempt_invoice.exempt_invoice_items.each_with_index do |i,n|%>
                    <tr>
                      <td><%= n + 1 %></td>
                      <td><%= i.item.dogns%></td>
                      <td><%= i.item.item_hsn_no%></td>
                      <td><%= i.item.unit_of_measure.name%></td>
                      <td>&#8377;<%= i.unit_price%></td>
                      <td><%= i.quantity%></td>
                      <td>&#8377;<%= i.net_amt%></td>
                      <td><%= i.tax_rate%>&#37;</td>
                      <td>CGST+SGST</td>
                      <td>&#8377;<%= i.tax_amt%></td>
                      <td align="right">&#8377;<%= i.total_amt%></td>
                    </tr>
                    <% tax_amt += i.tax_amt.to_f%>
                    <%total_amt += i.total_amt.to_f%>
                    <% end %>

                    <tr>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td>Total Tax: &#8377;<%=tax_amt%></td>
                      <td>Total Amount: &#8377;<%= total_amt%></td>
                    </tr>

                    
                  </div>
                </div>
              </div>
            </div>
          </div>